### PR TITLE
[Fixes #56] Fix CORS Issue

### LINKED ISSUE #56: Fix CORS issue
- [ ] For development API / client
- [ ] For production API / client (docker stack)

### PR DESCRIPTION
**Pull request by cascadianblue**
The web client was making API calls to the wrong port, and therefore triggering CORS. The docker-compose stack should work in any normal browser now.

Depends on #66

### CODE REVIEW

**Comment by tschaffter** [comment]
The fix should make it possible to use the app with and without docker.

**Comment by cascadianblue** [comment]
Here's the package that we could use to allow CORS requests to the API. Mainly the info that we have to provide is the `CORS_ORIGIN`, which would have to be either `'*'` (we allow cross-origin requests from any client; this seems unnecessarily loose security-wise) or we create a list of allowed origins (which would be one item containing the hostname [including port] that the web client is being served from, e.g. `"http://localhost:80"`).

I'm not sure where to get that list of allowed origins from. The `Config` has an items for `SERVER_HOST`, `SERVER_PORT`, `SERVER_PROTOCOL` for the backend, but nothing for the front end. Should we add that for the front end?

**Comment by tschaffter** [comment]
Depends on #66

**Comment by tschaffter** [comment]
@cascadianblue I'm merging this PR so that 1) I can deploy a preview version of the app on AWS, 2) we can get feedback on the UI from react engineers, and 3) we can start integrating this app to the CloudFormation template we will develop to easily deploy the full NLP Sandbox stack to Sage AWS production environment. I'll also create a "docker-compose.yml" to enable a user to deploy the full stack anywhere and play with it (I will host this `docker-compose.yml` in the [main repo](https://github.com/nlpsandbox/nlpsandbox)).

**Pull request merged**
