### PR TITLE
Increase Buffer Size

### PR DESCRIPTION
**Pull request by cascadianblue**
The NginX reverse proxy sometimes increases the request block sizes to more than the default maximum for this server. This fixes issue nlpsandbox/phi-deidentifier-app#46.

### CODE REVIEW

**Comment by cascadianblue** [comment]
@tschaffter any chance of getting this merged soon? It's currently a breaking bug in production

**Comment by tschaffter** [comment]
> It's currently a breaking bug in production

@cascadianblue Sorry about the late reply. If the solution solves the issue, then I'm going to merge even if we don't understand the issue yet. I'll find a way to keep this issue on my radar.

**Comment by tschaffter** [comment]
@cascadianblue Can you please describe where the value `buffer-size=32768` comes from?

**Comment by cascadianblue** [comment]
@tschaffter `32768 = 2^15`. It is a somewhat arbitrary number (the [upper limit](https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html#:~:text=By%20default%20uWSGI%20allocates%20a,with%20the%20buffer%2Dsize%20option.) on buffer size is `2^16 -  1 = 65535`).

We can set it smaller if you prefer (I don't think any of the blocks I observed in the error logs were larger than the `5000`s), but I think it should be at least `2^13 = 8192`.

**Pull request merged**
