### PR TITLE
Enable nginx to be reached but disable internet access to annotators

### PR DESCRIPTION
**Pull request by tschaffter**
This PR blocks network access to the services that are only in the network `nlp-sandbox-internal`. The reverse proxy (nginx) is a member of this network so that it can communicate with the dependencies (annotators). It's also a member of `nlp-sandbox`, which enables the PHI Deidentifier app and API to be reached from the host.

I checked that network access was disabled by running `docker exec -it container_id bash` and tried `apt update`.

### CODE REVIEW

**Comment by thomasyu888** [comment]
Looks good but has this been tested? Since internal isn't documented in docker-compose just want to make sure it works.

**Review by thomasyu888 — APPROVED** [review]

**Comment by tschaffter** [comment]
> I checked that network access was disabled by running `docker exec -it container_id bash` and tried apt update.

Do you have other tests in mind?

**Comment by thomasyu888** [comment]
> > I checked that network access was disabled by running `docker exec -it container_id bash` and tried apt update.
> 
> Do you have other tests in mind?

Sorry. I totally missed that.... Thanks!

**Comment by tschaffter** [comment]
I installed `dig` as part of the Dockerfile of the PHI API. The output below shows that the PHI deidentifier API cannot reach `google.com`.

image

Now if I add `dig` to the nginx container (`RUN apk update && apk add bind-tools`), this shows that this container has access to the host network and internet. Hopefully the user can trust the official nginx docker image. The only thing that we add to it is the nginx configuration.

image

**Pull request merged**
