### PR TITLE
[Implements #37] Dockerize the Web Client

### PR DESCRIPTION
**Pull request by cascadianblue**

### CODE REVIEW

**Comment by tschaffter** [comment]
@cascadianblue I have an error when I try to deid a note.

image

Steps to reproduce:
1. Type "plop" in the input field
2. Click on the button "De-identify Note"

Logs:

```
person-name-annotator         | detected max file descriptor number: 1048576
person-name-annotator         | lock engine: pthread robust mutexes
person-name-annotator         | thunder lock: enabled
person-name-annotator         | uwsgi socket 0 bound to TCP address :8080 fd 3
person-name-annotator         | Python version: 3.8.6 (default, Nov 25 2020, 02:47:44)  [GCC 8.3.0]
deidentifier-client           | /docker-entrypoint.sh: Configuration complete; ready for start up
person-name-annotator         | Python main interpreter initialized at 0x55d46fb4bf40
person-name-annotator         | python threads support enabled
person-name-annotator         | your server socket listen backlog is limited to 100 connections
person-name-annotator         | your mercy for graceful operations on workers is 60 seconds
physical-address-annotator    | Python main interpreter initialized at 0x55ba51b35330
physical-address-annotator    | python threads support enabled
physical-address-annotator    | your server socket listen backlog is limited to 100 connections
physical-address-annotator    | your mercy for graceful operations on workers is 60 seconds
physical-address-annotator    | mapped 145808 bytes (142 KB) for 1 cores
physical-address-annotator    | *** Operational MODE: single process ***
physical-address-annotator    | *** uWSGI is running in multiple interpreter mode ***
physical-address-annotator    | spawned uWSGI master process (pid: 1)
date-annotator                | spawned uWSGI worker 1 (pid: 14, cores: 1)
person-name-annotator         | mapped 145808 bytes (142 KB) for 1 cores
physical-address-annotator    | spawned uWSGI worker 1 (pid: 14, cores: 1)
physical-address-annotator    | spawned uWSGI http 1 (pid: 15)
physical-address-annotator    | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55ba51b35330 pid: 14 (default app)
phi-deidentifier              | *** Operational MODE: single process ***
phi-deidentifier              | *** uWSGI is running in multiple interpreter mode ***
phi-deidentifier              | spawned uWSGI master process (pid: 1)
phi-deidentifier              | spawned uWSGI worker 1 (pid: 13, cores: 1)
person-name-annotator         | *** Operational MODE: single process ***
person-name-annotator         | *** uWSGI is running in multiple interpreter mode ***
person-name-annotator         | spawned uWSGI master process (pid: 1)
person-name-annotator         | spawned uWSGI worker 1 (pid: 14, cores: 1)
date-annotator                | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55b3fcbb2f40 pid: 14 (default app)
phi-deidentifier              | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x561e23a6af40 pid: 13 (default app)
person-name-annotator         | WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55d46fb4bf40 pid: 14 (default app)
deidentifier-client           | 172.24.0.1 - - [27/Jan/2021:01:28:41 +0000] "GET / HTTP/1.1" 200 3014 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0" "-"
deidentifier-client           | 172.24.0.1 - - [27/Jan/2021:01:28:41 +0000] "GET /static/css/main.95fdf74b.chunk.css HTTP/1.1" 200 2372 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0" "-"
deidentifier-client           | 172.24.0.1 - - [27/Jan/2021:01:28:41 +0000] "GET /static/js/2.a1d235f6.chunk.js HTTP/1.1" 200 143746 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0" "-"
deidentifier-client           | 172.24.0.1 - - [27/Jan/2021:01:28:41 +0000] "GET /static/js/main.97f62fc6.chunk.js HTTP/1.1" 200 18319 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0" "-"
deidentifier-client           | 172.24.0.1 - - [27/Jan/2021:01:28:41 +0000] "GET /favicon.ico HTTP/1.1" 200 3870 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0" "-"
deidentifier-client           | 172.24.0.1 - - [27/Jan/2021:01:28:41 +0000] "GET /logo192.png HTTP/1.1" 200 5347 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0" "-"
phi-deidentifier              | [pid: 13|app: 0|req: 1/1] 172.24.0.1 () {42 vars in 675 bytes} [Wed Jan 27 01:28:47 2021] OPTIONS /api/v1/deidentifiedNotes => generated 205 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
```

**Comment by tschaffter** [comment]
The issue is due to this:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/api/v1/deidentifiedNotes. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/api/v1/deidentifiedNotes. (Reason: CORS request did not succeed).
```

**Comment by cascadianblue** [comment]
> @cascadianblue Can you comment/confirm that this is the behavior you expect with this PR?
@tschaffter yep, this is expected behavior for this PR. Could you try running a browser with same-origin protection turned off and see if it works for you then? If you are on Linux and have Google Chrome, you can run it with the following command:

```
$ google-chrome --disable-web-security --user-data-dir=~/TEMP/
```

**Comment by tschaffter** [comment]
This PR seems to be based on [this article](https://mherman.org/blog/dockerizing-a-react-app/#production).

**Comment by cascadianblue** [comment]
> This PR seems to be based on [this article](https://mherman.org/blog/dockerizing-a-react-app/#production).

Yes, it is. Should I put that link somewhere in a comment or in the documentation?

**Comment by tschaffter** [comment]
> Yes, it is. Should I put that link somewhere in a comment or in the documentation?

No. Capturing it here is enough.

> Could you try running a browser with same-origin protection turned off and see if it works for you then? If you are on Linux and have Google Chrome, you can run it with the following command:

I don't use chrome on unix. I tried an extension to disable CORS on FF and Chrome but this does not help, the CORS error are still there. [Here](https://stackoverflow.com/questions/54246811/react-express-fetch-post-cors-error-response-to-preflight-request-doesnt-pass) a potential solution below that you have mentioned in the past. I'll accept this PR and start addressing #45 to solve this issue.

**Review by tschaffter — APPROVED** [review]
Aside the CORS error that was expected, this looks good! Thanks!

**Pull request merged**
