### PR TITLE
[Implements #38] Store De-id Configuration State in URL

### PR DESCRIPTION
**Pull request by cascadianblue**
This PR makes the client store the de-id configuration state in the URL. Every time the user changes, adds, or deletes a de-id config step, the URL gets changed. You can copy and paste the same URL to a different browser window/tab or refresh the page and it will have the same de-id configuration.

### CODE REVIEW

**Review by tschaffter — APPROVED** [review]
Looks good! The way the state of the app is saved to the URL lead to a very long URL that is not very sharable-friendly, but at least it works. We should keep this improvement on our radar.

**Comment by tschaffter** [comment]
@emmanmills I think that the way @cascadianblue saves the state of the app, i.e. capturing the state as a JSON object saved as one variable, is not conventional but it works. One drawback is that the resulting URL is quite long and not very friendly to share with someone else so this person can try the app. One idea I had was to encode the JSON object into one string of characters, making the URL + state of the app looks like https://myapp.org/?state=akjsdhjsahgduy23487658aysfdgfahgds... What are your thoughts? Thanks!

**Comment by cascadianblue** [comment]
The previous encoding method was getting tripped up by percent signs in the state (this seems to be a bigger [issue](https://github.com/ReactTraining/history/issues/505) with the react-router library). I fixed it by encoding every character into a base 36 integer and joining them all with hyphens. Not the most elegant solution but it seems to work fine with everything I tried on it (% signs, &'s, non-Ascii chars).

**Comment by tschaffter** [comment]
@cascadianblue It's not clear from your comment if your update addresses my above remark about encoding the state of the app into a single string of character. Is that the case?

**Comment by cascadianblue** [comment]
> @cascadianblue It's not clear from your comment if your update addresses my above remark about encoding the state of the app into a single string of character. Is that the case?

No, if anything the fix I just added makes the URL longer. However, it fixes the issue where non-latin characters were tripping up the state-saving (and state-loading) mechanism

**Pull request merged**
