### PR TITLE
Display Tool Dependencies on Front End

### PR DESCRIPTION
**Pull request by cascadianblue**
Adds a dialog box on the front end (activated [by default] by info button in top right corner) that shows version, etc. info for deidentifier and annotators.

Also animates addition + deletion of de-id steps

### CODE REVIEW

**Comment by tschaffter** [comment]
When starting the app for the first time, there was a popup with a spinning wheel. It took more than a few second so I interupted it by clicking on a button (was it a "Close" button?). I now see this popup, which does not include information about the physical address annotator.

image

**Review by tschaffter — CHANGES_REQUESTED** [review]
See comment in PR thread.

**Comment by cascadianblue** [comment]
@tschaffter could you navigate to [http://localhost:9002/api/v1/tool](http://localhost:9002/api/v1/tool) and see what you get (I'm guessing it will be an empty `{}` JSON object)? I think the most likely explanation for what you're seeing is that you are running version of the example address annotator that doesn't properly implement the `/tool` endpoint

**Comment by tschaffter** [comment]
I released a new version of the physical address annotator that fixes the `/tool` endpoint.

**Pull request merged**
